CREATE TABLE `ref_obat_briging` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_local` bigint(20) unsigned DEFAULT NULL COMMENT 'ID dari database lokal',
  `apol_kode` varchar(255) DEFAULT NULL,
  `apol_nama` varchar(255) DEFAULT NULL,
  `medication_idIHS` varchar(40) DEFAULT NULL,
  `kfa_code` varchar(255) DEFAULT NULL,
  `kfa_display` varchar(255) DEFAULT NULL,
  `kfa_system` varchar(255) DEFAULT NULL,
  `kfa_bza` text COMMENT 'Data JSON Zat Aktif',
  `kfa_kekuatan` varchar(255) DEFAULT NULL,
  `kfa_uom` varchar(255) DEFAULT NULL,
  `kfa_ucum` varchar(255) DEFAULT NULL,
  `kfa_route` varchar(255) DEFAULT NULL COMMENT 'rute pemberian obat',
  `kfa_form` varchar(255) DEFAULT NULL,
  `kfa_generic` tinyint(2) DEFAULT NULL COMMENT 'tipe obat generic 0 atau 1',
  `kfa_drugcontrol_code` varchar(255) DEFAULT NULL COMMENT 'code drug kontrol',
  `kfa_drugcontrol_name` varchar(255) DEFAULT NULL COMMENT 'kfa drug control nama: obat keras dkk..',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_id_local` (`id_local`),
  KEY `idx_kfa_code` (`kfa_code`),
  KEY `idx_apol_kode` (`apol_kode`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
