CREATE TABLE `ssht_observation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `observation_idIHS` char(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `encounter_idIHS` char(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `subject_idIHS` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `obs_code` varchar(12) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `obs_display` varchar(191) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `obs_value` varchar(9) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT '-',
  `intr_code` varchar(9) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `intr_display` varchar(191) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `rm` varchar(7) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `dok` varchar(14) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `status` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `obs_system` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `obs_valueString` text COLLATE utf8mb3_unicode_ci,
  `codeable_system` text COLLATE utf8mb3_unicode_ci,
  `codeable_value` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `codeable_display` varchar(191) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `intr_system` text COLLATE utf8mb3_unicode_ci,
  `performer_idIHS` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `category_system` text COLLATE utf8mb3_unicode_ci,
  `category_code` varchar(30) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `category_display` varchar(191) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ssht_observation_observation_idihs_index` (`observation_idIHS`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;