CREATE TABLE `ssht_medication_request` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `medicationrequest_idIHS` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `encounter_idIHS` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `identifier_noresep` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `identifier_noresep_index` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contained` text COLLATE utf8mb4_unicode_ci,
  `category_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category_display` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category_system` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rm` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subject_idIHS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dok` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requester_idIHS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dispense_interval` text COLLATE utf8mb4_unicode_ci,
  `expected_supply_duration` text COLLATE utf8mb4_unicode_ci,
  `number_repeat_allowed` text COLLATE utf8mb4_unicode_ci,
  `performer_org_idIHS` varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity_system` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity_code` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity_unit` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `quantity_value` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `authored_on` datetime DEFAULT NULL,
  `validity_period_start` datetime DEFAULT NULL,
  `validity_period_end` datetime DEFAULT NULL,
  `dosage_instruction` text COLLATE utf8mb4_unicode_ci,
  `status` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas_idIHS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas_nama` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas_ambil_idIHS` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `petugas_ambil_nama` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `local_id` bigint unsigned DEFAULT NULL,
  `send_at` datetime DEFAULT NULL,
  `payload` text COLLATE utf8mb4_unicode_ci,
  `send_error_message` text COLLATE utf8mb4_unicode_ci,
  `send_error_code` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `send_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'S=sukses, F=failed, P=pending, M=menunggu di mapping',
  `medication_idIHS` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_noresep_index` (`identifier_noresep_index`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;